# Generated by Django 3.1.4 on 2020-12-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
